name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
          - tag: "5.41"
          - tag: "5.40"
          - tag: "5.40-bullseye32"
          - tag: "5.36-debug"
          - tag: "5.36-debug32"
          - tag: "5.40-longdouble"
          - tag: "5.40-quadmath"
          - tag: "5.40-threads"
          - tag: "5.38"
          - tag: "5.36"
          - tag: "5.34"
          - tag: "5.32"
          - tag: "5.30"
          - tag: "5.28"
          - tag: "5.26"
          - tag: "5.24"
          - tag: "5.22"
          - tag: "5.20"

    env:
      CIP_TAG: ${{ matrix.cip.tag }}
      CIP_ENV: ${{ matrix.cip.env }}

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap CIP
        run: curl -L https://raw.githubusercontent.com/uperl/cip/main/bin/github-bootstrap | bash

      - name: Start Container
        run: cip start

      - name: Diagnostics
        run: cip diag

      - name: Build
        run: cip exec make

      - name: Test
        run: cip exec prove -vm
